require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailUsersController do

  # This should return the minimal set of attributes required to create a valid
  # MailUser. As you add validations to MailUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mail_users as @mail_users" do
      mail_user = MailUser.create! valid_attributes
      get :index
      assigns(:mail_users).should eq([mail_user])
    end
  end

  describe "GET show" do
    it "assigns the requested mail_user as @mail_user" do
      mail_user = MailUser.create! valid_attributes
      get :show, :id => mail_user.id.to_s
      assigns(:mail_user).should eq(mail_user)
    end
  end

  describe "GET new" do
    it "assigns a new mail_user as @mail_user" do
      get :new
      assigns(:mail_user).should be_a_new(MailUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested mail_user as @mail_user" do
      mail_user = MailUser.create! valid_attributes
      get :edit, :id => mail_user.id.to_s
      assigns(:mail_user).should eq(mail_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailUser" do
        expect {
          post :create, :mail_user => valid_attributes
        }.to change(MailUser, :count).by(1)
      end

      it "assigns a newly created mail_user as @mail_user" do
        post :create, :mail_user => valid_attributes
        assigns(:mail_user).should be_a(MailUser)
        assigns(:mail_user).should be_persisted
      end

      it "redirects to the created mail_user" do
        post :create, :mail_user => valid_attributes
        response.should redirect_to(MailUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mail_user as @mail_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailUser.any_instance.stub(:save).and_return(false)
        post :create, :mail_user => {}
        assigns(:mail_user).should be_a_new(MailUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailUser.any_instance.stub(:save).and_return(false)
        post :create, :mail_user => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mail_user" do
        mail_user = MailUser.create! valid_attributes
        # Assuming there are no other mail_users in the database, this
        # specifies that the MailUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailUser.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mail_user.id, :mail_user => {'these' => 'params'}
      end

      it "assigns the requested mail_user as @mail_user" do
        mail_user = MailUser.create! valid_attributes
        put :update, :id => mail_user.id, :mail_user => valid_attributes
        assigns(:mail_user).should eq(mail_user)
      end

      it "redirects to the mail_user" do
        mail_user = MailUser.create! valid_attributes
        put :update, :id => mail_user.id, :mail_user => valid_attributes
        response.should redirect_to(mail_user)
      end
    end

    describe "with invalid params" do
      it "assigns the mail_user as @mail_user" do
        mail_user = MailUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailUser.any_instance.stub(:save).and_return(false)
        put :update, :id => mail_user.id.to_s, :mail_user => {}
        assigns(:mail_user).should eq(mail_user)
      end

      it "re-renders the 'edit' template" do
        mail_user = MailUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailUser.any_instance.stub(:save).and_return(false)
        put :update, :id => mail_user.id.to_s, :mail_user => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mail_user" do
      mail_user = MailUser.create! valid_attributes
      expect {
        delete :destroy, :id => mail_user.id.to_s
      }.to change(MailUser, :count).by(-1)
    end

    it "redirects to the mail_users list" do
      mail_user = MailUser.create! valid_attributes
      delete :destroy, :id => mail_user.id.to_s
      response.should redirect_to(mail_users_url)
    end
  end

end
